### ISSUE TITLE
no energy sensors in fullrules-build

### ISSUE THREAD

**Issue by manuelm** [Jason2866/Tasmota-build#12]
Hi.

Just wanted to test out the "fullrules"-build, but noticed that my/all energy sensor/s is/are missing. Is this intended? Because `USE_ENERGY_MARGIN_DETECTION` and `USE_ENERGY_POWER_LIMIT` is defined in https://github.com/Jason2866/Tasmota-build/blob/special_builder/tasmota/user_config_override.h#L2601, but `USE_ENERGY_SENSOR` is missing. Making the former kind of useless?

**Comment by Jason2866** [comment]
Yes, as intended. The built does include some energy sensors.
There are now already a lot of. Which do you think are useful to include?
All is not possible.

**Comment by manuelm** [comment]
BL0937. But you don't need to change anything. I was just wondering why it's in the default build, but not in fullrules.

I build my own version a few minutes after noticing. Thank you for your help.

**Comment by Jason2866** [comment]
Removed. The firmware increased too much, so no OTA was possible anymore.
