### ISSUE TITLE
No driver for SH1106 (I2Cdriver Index 6) in Platinum build

### ISSUE THREAD

**Issue by thomas-lentz** [Jason2866/Tasmota-build#16]
### PROBLEM DESCRIPTION
The **Tasmota Platinum**  version is huge, but unfortunately not huge enough anymore... 
For an unknown reason the I2C driver:

`6 | USE_DISPLAY_SH1106 | xdsp_07 | SH1106 | 0x3C - 0x3D | Oled display`

is not contained anymore. It was in an older version, which I was running on my [AirGradient Pro Version DIY Air Quality Sensor](https://templates.blakadder.com/air-gradient-pro.html).

The SSH1106 is working fine, when I use the 13.4.0(display), but then there are no sensor available for the Air-Quality measurement.

`{"StatusFWR":{"Version":"13.4.0(display)","BuildDateTime":"2024-02-14T16:13:52","Boot":18,"Core":"2_7_6","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"420/699"}}`

Of ourse I could just enable the driver and compile it for myself, but since Tasmota Platinum is referenced [here](https://templates.blakadder.com/air-gradient-pro.html) I would prefer a fix in the Tasmota Platinum version. Thanks in advance.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): ESP8266EX/AirGradient Pro Version DIY Air Quality Sensor
- [x] Tasmota binary firmware version number used: **13.4.1.2(157e1af-platinum)**
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: [Tasmota Web-Installer](https://tasmota.github.io/install/)
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
20:52:32.752 CMD: Backlog Template; Module; GPIO 255
20:52:32.847 MQT: stat/xxx/airgradient-restaurant/RESULT = {"NAME":"AirGradient Pro","GPIO":[1600,1,1632,0,640,608,1,1,1664,1,1696,1,1,1],"FLAG":0,"BASE":18}
20:52:33.073 MQT: stat/xxx/airgradient-restaurant/RESULT = {"Module":{"0":"AirGradient Pro"}}
20:52:33.279 MQT: stat/xxx/airgradient-restaurant/RESULT = {"GPIO0":{"1600":"SAir Tx"},"GPIO1":{"0":"None"},"GPIO2":{"1632":"SAir Rx"},"GPIO3":{"0":"None"},"GPIO4":{"640":"I2C SDA"},"GPIO5":{"608":"I2C SCL"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO12":{"1664":"PMS5003 Tx"},"GPIO13":{"0":"None"},"GPIO14":{"1696":"PMS5003 Rx"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"}}

```
- [x] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
20:53:33.587 CMD: Backlog Rule1; Rule2; Rule3
20:53:33.662 MQT: stat/xxx/airgradient-restaurant/RESULT = {"Rule1":{"State":"ON","Once":"OFF","StopOnError":"OFF","Length":35,"Free":476,"Rules":"ON System#Boot DO power on ENDON ON"}}
20:53:33.884 MQT: stat/xxx/airgradient-restaurant/RESULT = {"Rule2":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}
20:53:34.102 MQT: stat/xxx/airgradient-restaurant/RESULT = {"Rule3":{"State":"OFF","Once":"OFF","StopOnError":"OFF","Length":0,"Free":511,"Rules":""}}

```
- [x] Provide the output of this command: `Status 0`:
```lua
20:45:34.870 MQT: tele/xxx/airgradient-restaurant/STATE = {"Time":"2024-04-22T20:45:34","Uptime":"0T00:05:09","UptimeSec":309,"Heap":8,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":21,"MqttCount":1,"POWER":"ON","Wifi":{"AP":2,"SSId":"myEdge","BSSId":"F6:02:28:09:21:F1","Channel":6,"Mode":"11n","RSSI":72,"Signal":-64,"LinkCount":1,"Downtime":"0T00:00:04"}}
20:45:34.906 MQT: tele/xxx/airgradient-restaurant/SENSOR = {"Time":"2024-04-22T20:45:34","BMP280":{"Temperature":26.7,"Pressure":1017.2},"S8":{"CarbonDioxide":1010},"PMS5003":{"CF1":9,"CF2.5":13,"CF10":13,"PM1":9,"PM2.5":13,"PM10":13,"PB0.3":1623,"PB0.5":477,"PB1":66,"PB2.5":5,"PB5":0,"PB10":0},"Thermostat1":{"ThermostatModeSet":0,"TempTargetSet":18.00,"CtrDutyCycleRead":0,"ControlMethod":0,"HybridControllerPhase":1,"EmergencyState":0},"PressureUnit":"hPa","TempUnit":"C"}
20:45:48.595 MQT: stat/xxx/airgradient-restaurant/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":" ","RestartReason":"Exception","Uptime":"0T00:05:23","StartupUTC":"2024-04-22T19:40:25","Sleep":50,"CfgHolder":4617,"BootCount":76,"BCResetTime":"2024-04-19T21:12:47","SaveCount":1178,"SaveAddress":"FC000"}}
20:45:48.624 MQT: stat/xxx/airgradient-restaurant/STATUS2 = {"StatusFWR":{"Version":"13.4.1.2(157e1af-platinum)","BuildDateTime":"2024-04-22T07:42:51","Boot":31,"Core":"2_7_6","SDK":"2.2.2-dev(38a443e)","CpuFrequency":160,"Hardware":"ESP8266EX","CR":"420/699"}}
20:45:48.650 MQT: stat/xxx/airgradient-restaurant/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["xxx","myEdge"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","00000080","00006000","00004000","00000000"]}}
20:45:48.686 MQT: stat/xxx/airgradient-restaurant/STATUS4 = {"StatusMEM":{"ProgramSize":939,"Free":1108,"Heap":5,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"164068","FlashFrequency":40,"FlashMode":"DOUT","Features":["0809","9FBAC78F","0427EAA1","FFF7B7CF","CFFC9FFF","ECAFFFF7","082044BF","20248000","54082020","00000080","00000000"],"Drivers":"1,2,!3,!4,!5,!6,7,!8,9,10,11,12,13,!14,!15,!16,!17,!18,!19,!20,!22,!24,!25,26,!27,!28,29,!30,31,32,!34,!35,!36,!37,38,39,50,!60,62,!66","Sensors":"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,24,26,27,29,30,31,32,34,37,38,39,40,41,42,43,44,45,46,50,51,52,54,55,56,57,59,62,64,65,66,91","I2CDriver":"1,!2,3,5,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,24,25,28,29,30,31,32,34,35,36,39,40,42,44,45,46,47"}}
20:45:48.750 MQT: stat/xxx/airgradient-restaurant/STATUS5 = {"StatusNET":{"Hostname":"airgradient-restaurant","IPAddress":"192.168.107.103","Gateway":"192.168.107.178","Subnetmask":"255.255.255.0","DNSServer1":"192.168.107.178","DNSServer2":"0.0.0.0","Mac":"34:94:54:61:E2:08","Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":17.0}}
20:45:48.779 MQT: stat/xxx/airgradient-restaurant/STATUS6 = {"StatusMQT":{"MqttHost":"xxxxxx","MqttPort":1883,"MqttClientMask":"airgradient-restaurant","MqttClient":"airgradient-restaurant","MqttUser":"iot-user","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
20:45:48.805 MQT: stat/xxx/airgradient-restaurant/STATUS7 = {"StatusTIM":{"UTC":"2024-04-22T19:45:48Z","Local":"2024-04-22T20:45:48","StartDST":"2024-03-31T02:00:00","EndDST":"2024-10-27T03:00:00","Timezone":"+01:00","Sunrise":"05:44","Sunset":"19:52"}}
20:45:48.830 MQT: stat/xxx/airgradient-restaurant/STATUS10 = {"StatusSNS":{"Time":"2024-04-22T20:45:48","BMP280":{"Temperature":26.8,"Pressure":1017.2},"S8":{"CarbonDioxide":1011},"PMS5003":{"CF1":8,"CF2.5":14,"CF10":14,"PM1":8,"PM2.5":14,"PM10":14,"PB0.3":1554,"PB0.5":467,"PB1":108,"PB2.5":10,"PB5":0,"PB10":0},"Thermostat1":{"ThermostatModeSet":0,"TempTargetSet":18.00,"CtrDutyCycleRead":0,"ControlMethod":0,"HybridControllerPhase":1,"EmergencyState":0},"PressureUnit":"hPa","TempUnit":"C"}}
20:45:48.872 MQT: stat/xxx/airgradient-restaurant/STATUS11 = {"StatusSTS":{"Time":"2024-04-22T20:45:48","Uptime":"0T00:05:23","UptimeSec":323,"Heap":7,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":2,"SSId":"myEdge","BSSId":"F6:02:28:09:21:F1","Channel":6,"Mode":"11n","RSSI":74,"Signal":-63,"LinkCount":1,"Downtime":"0T00:00:04"}}}
20:45:48.902 MQT: stat/xxx/airgradient-restaurant/STATUS12 = {"StatusSTK":{"Exception":28,"Reason":"Exception","EPC":["4027d9f8","00000000","00000000"],"EXCVADDR":"0000000c","DEPC":"00000000","CallChain":["40295e10","40226b0f","40226c7f","40287d44","4023c14c","40226cfe","4023c1c2","4023b560","4025b4f4","4024747b","402496fb","40269e14","40269e4c","40100eb0","402890c4","40102245"]}}

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
20:55:12.423 CMD: displaymodel 7
20:55:12.424 SRC: WebConsole from 192.168.107.216
20:55:12.426 CMD: Grp 0, Cmd 'DISPLAYMODEL', Idx 1, Len 1, Pld 7, Data '7'
20:55:12.431 MQT: stat/xxx/airgradient-restaurant/RESULT = {"DisplayModel":1}
```

### TO REPRODUCE
Install the Tasmota Platinium with an SH1106 connected to the I2C and try to activate it with `displaymodel 7`

### EXPECTED BEHAVIOUR
The I2Cdriver with Index 6 is available and SH1106 can be selected with Displaymodel 7

### SCREENSHOTS
```
20:41:10.642 CMD: i2cdriver
20:41:10.649 MQT: stat/xxx/airgradient-restaurant/RESULT = {"I2CDriver":"1,!2,3,5,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,24,25,28,29,30,31,32,34,35,36,39,40,42,44,45,46,47"}
```
Trying to set Displaymodel 7[ (SH1106 OLED display)](https://tasmota.github.io/docs/Displays/#supported-displays):

```
20:42:17.877 CMD: displaymodel 7
20:42:17.883 MQT: stat/xxx/airgradient-restaurant/RESULT = {"DisplayModel":1}

```
### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
As designed. https://github.com/arendst/Tasmota/pull/21183
Have to change to include UDisplay driver.

**Comment by Jason2866** [comment]
Changed with latest commit. New builds with the change and including UDisplay driver when a commit in Tasmota main repo is done.
Migration info https://tasmota.github.io/docs/Universal-Display-Driver/#migrating-to-udisplay

**Comment by thomas-lentz** [comment]
Well, I spent more than 4 hours now and before I drill deeper into the problem:

**Did anybody actually test the udriver functionality with an I2C display or any display in the ESP8266 Tasmota Platinum release 13.4.1.2(157e1af-platinum)?**

I don't want to go through the hassle of gathering all the "necessary" information for the bug report if nobody tested the function initially. I'm configuring the device by heart in the meantime (so often I followed the migration instructions).

The udriver just doesn't get activated with option A3. Doesn't matter if it is in the template (activated) or in the module configuration. You can set it manually and it isn't set automatically. I2cscan see the display at 0x3c. The corresponding display.ini is copied.
The display is working when I use the "normal" Tasmota display firmware.
Also it seems to me as if the Tasmota Platinum Version is the only ESP8266 version currently "featuring" the "Manage Filesystems" functionality - is this really working?!?

I erased the device x times. It is just not working! Could please somebody help.

I already worked with the udriver to get an ESP display (with no ready to go display.ini) to work. uDriver is completely free of fun...
It is easier for me to write a new driver for the waveshare display (change an existing one) than get a new display.ini to work with the udriver. But that is another problem. Now I just want the SH1106 back to work again!

Jason: Maybe you can provide me with the latest Tasmota Platinum ESP8266 Firmware version without uDriver enforced SH1106 support (meaning i2cdriver6 still available :o)?

**Comment by Jason2866** [comment]
Have you compiled the Platinum firmware yourself? The change is not yet in the precompiled platinum firmware. There was not commit in Theos repo after i made the changes here which triggers a build.
There will no support for displays with dedicated drivers. The are removed from the source code. If you want to use, use a older build.
To be clear the builded variants here will be always based on latest development branch/commit.
There are no changes in source code done.

**Comment by thomas-lentz** [comment]
No, I didn't compile it myself. I used the version you get offered by the standard installer you can get from https://tasmota.github.io/install/
Flashed it with MS-Edge.
This installs the uDriver enforced version "Version":"13.4.1.2(157e1af-platinum) Taken of Status 0

![2024-04-23 (2)](https://github.com/Jason2866/Tasmota-build/assets/53970628/325321c8-3da2-43ea-aac1-4d997d8728e3)

**Comment by Jason2866** [comment]
So, the uDisplay driver was not yet included. It is now. A commit was done around a hour ago in Theos repo.

**Comment by thomas-lentz** [comment]
Okay, I gave up for the time being and compiled a current Tasamota sensor version with activated use_display directive, with a revived displaydriver 6 (removed the comment flags in the driver file) and an old Adafruit_SH1106 Library, which I copied from an older Tasmota version.
I will check again, when somebody confirms that he saw the uDriver running with an OLED display ;-)
