### ISSUE TITLE
Adding a USE_PROMETHEUS build

### ISSUE THREAD

**Issue by MarkusTeufelberger** [Jason2866/Tasmota-build#8]
Hi there, I'd like to tackle the issue of adding an unofficial build for the standard (and maybe the "sensors") version of Tasmota, just with `USE_PROMETHEUS` also defined in there. See also https://github.com/arendst/Tasmota/issues/9206

Is this the correct repository to do so?

I hope it is just as easy as adding

```
[env:tasmota-prometheus]
build_flags = ${env.build_flags} -DUSE_PROMETHEUS

[env:tasmota-sensors-prometheus]
build_flags             = ${env.build_flags} -DFIRMWARE_SENSORS -DUSE_PROMETHEUS
lib_extra_dirs          = lib/lib_basic, lib/lib_i2c, lib/lib_rf, lib/lib_div
```

into `platformio_tasmota_cenv.ini`?

**Comment by Jason2866** [comment]
There is already a unofficial env `allsensors` for esp8266 and esp32.
See `platformio_tasmota_cenv.ini` Please add the needed settings for Prometheus in
file `user_config_override.h` in folder `Tasmota`

**Comment by Jason2866** [comment]
Added to Allsensors with https://github.com/Jason2866/Tasmota-build/commit/d59752a7c3654bb22ab2e937d8d4a5265267d4e6
